module.exports = {
	CLASS_RECURRANCE_TYPE_DAILY: "CLASS_RECURRANCE_TYPE_DAILY",
	CLASS_RECURRANCE_TYPE_WEEKLY: "CLASS_RECURRANCE_TYPE_WEEKLY",
	CLASS_RECURRANCE_TYPE_FORTNIGHTLY: "CLASS_RECURRANCE_TYPE_FORTNIGHTLY",
	CLASS_RECURRANCE_TYPE_MONTHLY: "CLASS_RECURRANCE_TYPE_MONTHLY",
};
