module.exports = {
  EVENT_QUEUE: 'EVENT_QUEUE',

  EVENT_CONTROLS: 'EVENT_CONTROLS',

  EVENT_QUEUE_PUSH: 'EVENT_QUEUE_PUSH',

  EVENT_QUEUE_POP: 'EVENT_QUEUE_POP',

  EVENT_QUEUE_CLEAR: 'EVENT_QUEUE_CLEAR',
}
