module.exports = {
  JOB_STATUS_PENDING: 'JOB_STATUS_PENDING',
  JOB_STATUS_RUNNING: 'JOB_STATUS_RUNNING',
  JOB_STATUS_COMPLETED: 'JOB_STATUS_COMPLETED',
  JOB_STATUS_FAILED: 'JOB_STATUS_FAILED',
  JOB_STATUS_CANCELLED: 'JOB_STATUS_CANCELLED',
}
