module.exports = {
	USER_PLAN_ACTIVE: "ACTIVE",
	USER_PLAN_INACTIVE: "INACTIVE",
	USER_PLAN_CANCELLED: "CANCELLED",
	USER_PLAN_FINISHED: "FINISHED",
	USER_PLAN_EXPIRED: "EXPIRED",
	USER_PLAN_STAGED: "STAGED",
};
