module.exports = {
	USER_PLAN_ACTIVE: "ACTIVE",
	USER_PLAN_CANCELLED: "CANCELLED",
	USER_PLAN_EXPIRED_BY_DATE: "EXPIRED_BY_DATE",
	USER_PLAN_EXPIRED_BY_USAGE: "EXPIRED_BY_USAGE",
	USER_PLAN_STAGED: "STAGED",
};
