export const CLASS_TYPE_ONETIME = "CLASS_TYPE_ONETIME",
	CLASS_TYPE_RECURRING = "CLASS_TYPE_RECURRING";

export const CLASS_RECURRANCE_TYPE_DAILY = "CLASS_RECURRANCE_TYPE_DAILY",
	CLASS_RECURRANCE_TYPE_WEEKLY = "CLASS_RECURRANCE_TYPE_WEEKLY",
	CLASS_RECURRANCE_TYPE_FORTNIGHTLY = "CLASS_RECURRANCE_TYPE_FORTNIGHTLY",
	CLASS_RECURRANCE_TYPE_MONTHLY = "CLASS_RECURRANCE_TYPE_MONTHLY";
