export const EVENT_QUEUE = "EVENT_QUEUE",
	EVENT_CONTROLS = "EVENT_CONTROLS",
	EVENT_TIMER = "EVENT_TIMER";

export const EVENT_QUEUE_PUSH = "EVENT_QUEUE_PUSH",
	EVENT_QUEUE_POP = "EVENT_QUEUE_POP",
	EVENT_QUEUE_CLEAR = "EVENT_QUEUE_CLEAR";

export const EVENT_CONTROLS_PLAY = "EVENT_CONTROLS_PLAY",
	EVENT_CONTROLS_PAUSE = "EVENT_CONTROLS_PAUSE",
	EVENT_CONTROLS_NEXT = "EVENT_CONTROLS_NEXT",
	EVENT_CONTROLS_PREV = "EVENT_CONTROLS_PREV",
	EVENT_CONTROLS_SEEK_TO = "EVENT_CONTROLS_SEEK_TO",
	EVENT_CONTROLS_SEEK_MARKER = "EVENT_CONTROLS_SEEK_MARKER";
