steps:
  WORKDIR "/backend"
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/am-yoga-website/github.com/dev-6amyoga/yoga-website:$COMMIT_SHA",
        "-f",
        "./backend/Dockerfile",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/am-yoga-website/github.com/dev-6amyoga/yoga-website:$COMMIT_SHA",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "backend",
        "--image",
        "gcr.io/am-yoga-website/github.com/dev-6amyoga/yoga-website:$COMMIT_SHA",
        "--region",
        "asia-southeast1",
      ]
images:
  - gcr.io/am-yoga-website/github.com/dev-6amyoga/yoga-website:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
