export default function ShakaIframe() {
	return (
		<div className="max-w-7xl mx-auto">
			<h1>ShakaIframe</h1>
			<div className="max-w-4xl mx-auto">
				<iframe
					src="https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;assetBase64=eyJuYW1lIjoieHgiLCJzaG9ydE5hbWUiOiIiLCJpY29uVXJpIjoiIiwibWFuaWZlc3RVcmkiOiJodHRwczovL3B1Yi0wZjgyMWQ4YWEwYjA0NDZjYWUwNjEzNzg4YWQyMWFiYy5yMi5kZXYvNjZhMGM4MWZlYjcxOTJmYmI4ZDk5ODQ0Lm1wZCIsInNvdXJjZSI6IkN1c3RvbSIsImZvY3VzIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJleHRyYVRleHQiOltdLCJleHRyYVRodW1ibmFpbCI6W10sImV4dHJhQ2hhcHRlciI6W10sImNlcnRpZmljYXRlVXJpIjpudWxsLCJkZXNjcmlwdGlvbiI6bnVsbCwiaXNGZWF0dXJlZCI6ZmFsc2UsImRybSI6WyJObyBEUk0gcHJvdGVjdGlvbiJdLCJmZWF0dXJlcyI6WyJWT0QiXSwibGljZW5zZVNlcnZlcnMiOnsiX190eXBlX18iOiJtYXAifSwibGljZW5zZVJlcXVlc3RIZWFkZXJzIjp7Il9fdHlwZV9fIjoibWFwIn0sInJlcXVlc3RGaWx0ZXIiOm51bGwsInJlc3BvbnNlRmlsdGVyIjpudWxsLCJjbGVhcktleXMiOnsiX190eXBlX18iOiJtYXAifSwiZXh0cmFDb25maWciOnsic3RyZWFtaW5nIjp7ImJ1ZmZlcmluZ0dvYWwiOjEwLCJidWZmZXJCZWhpbmQiOjIwLCJyZWJ1ZmZlcmluZ0dvYWwiOjQsImlnbm9yZVRleHRTdHJlYW1GYWlsdXJlcyI6dHJ1ZSwic3RhbGxUaHJlc2hvbGQiOjMsInNlZ21lbnRQcmVmZXRjaExpbWl0IjozLCJwcmVsb2FkTmV4dFVybFdpbmRvdyI6NDAsInJldHJ5UGFyYW1ldGVycyI6eyJtYXhBdHRlbXB0cyI6MywidGltZW91dCI6MzAwMDAsImNvbm5lY3Rpb25UaW1lb3V0IjozMDAwMCwic3RhbGxUaW1lb3V0IjoxNTAwMH19LCJhYnIiOnsiZW5hYmxlZCI6dHJ1ZSwiZGVmYXVsdEJhbmR3aWR0aEVzdGltYXRlIjoxMDAwMDAwLCJzd2l0Y2hJbnRlcnZhbCI6OCwiYmFuZHdpZHRoVXBncmFkZVRhcmdldCI6MC44NSwiYmFuZHdpZHRoRG93bmdyYWRlVGFyZ2V0IjowLjk1fX0sImV4dHJhVWlDb25maWciOm51bGwsImFkVGFnVXJpIjpudWxsLCJpbWFWaWRlb0lkIjpudWxsLCJpbWFBc3NldEtleSI6bnVsbCwiaW1hQ29udGVudFNyY0lkIjpudWxsLCJpbWFNYW5pZmVzdFR5cGUiOm51bGwsIm1lZGlhVGFpbG9yVXJsIjpudWxsLCJtZWRpYVRhaWxvckFkc1BhcmFtcyI6bnVsbCwidXNlSU1BIjp0cnVlLCJtaW1lVHlwZSI6bnVsbH0=;panel=CUSTOM%20CONTENT;build=compiled"
					className="w-full h-[75vh]"
				/>
			</div>
		</div>
	);
}
